name: Deploy All Services from S3 to EKS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Update Kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ap-northeast-2 --name nsmm-eks

      - name: Download all YAMLs from S3
        run: |
          mkdir -p eks-yamls
          aws s3 cp s3://esg-storage-bucket/EKS/ ./eks-yamls/ --recursive

      - name: Apply YAMLs to EKS
        run: |
          find eks-yamls -type f -name "*.yaml" | while read file; do
            echo "▶️ Applying $file"
            kubectl apply -f "$file"
          done
